name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - uses: hashicorp/setup-terraform@v2
      - name: Configure Terraform Cloud credentials
        run: echo "credentials \"app.terraform.io\" { token = \"${TF_API_TOKEN}\" }" >> ~/.terraformrc
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform plan
        id: plan
        run: terraform plan
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -input=false
