name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Configure Terraform Cloud credentials
        run: echo "credentials \"app.terraform.io\" { token = \"${TF_API_TOKEN}\" }" >> ~/.terraformrc
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      # Optionally, you can run Terraform plan locally to preview changes
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # The apply operation will be triggered remotely by Terraform Cloud
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
